### ISSUE TITLE
NMON can't get disk information, nmon_external_start.sh insert wrong position

### ISSUE THREAD

**Issue by zbw1983** [guilhemmarchand/nmon-for-splunk#72]
Hi 

I am using syslog to collect nmon data, I have more than 100 servers, but on one of those, I found nmon_external_start.sh insert data after DISK section, it likes "JFSFILE,JFS Filespace %Used report06b,/,PROCCOUNT,Process Count,nb_running_processes", then splunk nmon can't get disk information. 

I suppose nmon_external_start.sh should insert contents at the first line of nmon_fifo file, but now it writes the line in the middle of file, I am not sure what's wrong, any idea? 

Regards

**Comment by guilhemmarchand** [comment]
Hello!

Ok, that's interesting, you say you are using syslog to collect the nmon data, does that mean that you are using the nmon-logger package I am providing ?

I would be keen to think that for some reasons the PROCCOUNT operation takes longer that expected.

In the "nmon_external_start.sh" script the task is being sent in the back ground (& at the end of the line), that could be an issue in that case.

Let's try to see how to improve that.

**Comment by zbw1983** [comment]
Thanks for your quick respond. 

Yes, I use nmon-logger package. This issue only on one server. On other servers, the first two lines in nmon_header.dat is "PROCCOUNT,Process Count,nb_running_processes
UPTIME,Server Uptime and load,uptime_stdout", but on the servers have this problem, the first line is "CPU001,CPU 1 report06b,User%,Sys%,Wait%,Idle%,Steal%" 

Beside this error message, on nmon page, on some servers, it also report some "notable events", said 

DISKBSIZE section data is not consistent: 20 fields in data, 7 fields in header, extra fields detected (more fields in data than header), dropping this section to prevent data inconsistency
DISKREAD section data is not consistent: 20 fields in data, 7 fields in header, extra fields detected (more fields in data than header), dropping this section to prevent data inconsistency
DISKWRITE section data is not consistent: 20 fields in data, 7 fields in header, extra fields detected (more fields in data than header), dropping this section to prevent data inconsistency
DISKXFER section data is not consistent: 20 fields in data, 7 fields in header, extra fields detected (more fields in data than header), dropping this section to prevent data inconsistency
NET section data is not consistent: 16 fields in data, 6 fields in header, extra fields detected (more fields in data than header), dropping this section to prevent data inconsistency

Seems something wrong with the nmon output format, but I can't say the exact error position, do you have any idea? 

All of my clients are RHEL7.1 or CentOS7.2. 

Regards

**Comment by guilhemmarchand** [comment]
Thank you.

I am looking at improving the external collection with logging the metrics into a dedicated file, this should solve this issue.

For the other servers issue, that should happen when there have some changes in the configuration, the headers definition runs every 24 hours and any change in this interval can generate this behaviour.

You could try to kill the running nmon process and check right after that if the problem still occurs ?

Thanks

**Comment by zbw1983** [comment]
Yes, seems "DISKBSIZE" error message disappear today. But wrong "PROCCOUNT" line problem happened on more servers, I found another 3 servers have this problem now. All problem is caused "PRCCOUNT" line is not at the beginning of nmon_header.dat. 

Any work around of this problem? 

Regards

**Comment by guilhemmarchand** [comment]
Hi !

I am working on a fix that manages the external metrics in a separated file.
Will update you very soon.

Regards,

**Comment by guilhemmarchand** [comment]
Hello !

A testing release of the nmon-logger is available in the testing branch (version 2.0.1):

https://github.com/guilhemmarchand/nmon-logger/tree/testing

It is currently under qualification, but for now all looks good.
The external metrics are now stored into a dedicated file instead of the named pipe, this is is expected to solve the issue you encounter.

If you the chance to test, that would be great.

Thank you!

Regards,

Guilhem

**Comment by zbw1983** [comment]
Thanks for your quick fix, but seems I still have this problem. I install this new package on my server, in my nmon_header.dat, I still find wrong format line: 
"JFSFILE,JFS Filespace %Used report06b,/,PROCCOUNT,Process Count,nb_running_processes"
I am not sure why it always happened on this server this line. very strange. 

And I also found a rpm install issue. When I use "rpm -Uvh" to upgrade nmon-logger-rsyslog, after I upgrade this package, there is no /etc/nmon-logger folder, it is deleted by nmon-logger-rsyslog postun scripts. I think it is caused by "rm -rf /etc/nmon-logger" command in postun section. If I use "rpm -Uvh" to install package, the postun scripts of old package will be run at last, then /etc/nmon-logger folder is disappear. Maybe you need check whether it is upgrade process or uninstall process before delete /etc/nmon-logger folder. 

Another question, I found the nmon.conf file is different with 2.0.0 version. Could you tell me why you have those changes? 
In new conf file. 
nmon_external_generation="1" (newly added): Suppose it is used for external scripts
mode_fifo="1" (newly added)
override_sys_hostname="0" (deleted from new conf)
nmon2csv_options="--mode fifo" (changed from realtime to fifo)

**Comment by guilhemmarchand** [comment]
Hi,

Thank you for your quick feedback.

Right, that's weird indeed, to be fair I misunderstood the issue as I thought the lines were in the data metric, not the headers.

There are some scripts involved in these steps:

- bin/fifo_reader.py | bin/fifo_reader.pl: depending on the Python (2.7.x) avaibility, the Python or Perl script starts and launches the "bin/fifo_reader.sh" that itself reads continuously the named pipe.

Then the Python / Perl identifies the nmon data (headers, metrics...) using regex.

For some unknown reasons, it seems that are no carriage return on this specific server.

**This can most probably be fixed by adding a supplementary (but normally not needed !) carriage return in the script:**

`/etc/nmon-logger/bin/nmon_external_cmd/nmon_external_start.sh`

**For verification purposes, could you please:**

- Modify the script and replace:

`# number of running processes
echo "PROCCOUNT,Process Count,nb_running_processes" >>NMON_FIFO_PATH`

By:

`# number of running processes
echo -e "\nPROCCOUNT,Process Count,nb_running_processes" >>NMON_FIFO_PATH`

- Kill the existing nmon process:

`pkill nmon`

After 1 minute max, a new process should be spawned, then check the nmon_headers.dat to verify the carriage **return.

*RPM issue:*

Thank you for reporting it, I will correct that **;-)

*Questions:*

To answer your questions:

- nmon_external_generation:

This switch allows activating / deactivating the nmon external data generation.
In other words, if switched off, the nmon_helper.sh will not export the variables that instruct the nmon binaries to run the external scripts.

- mode_fifo:

Allows activating the fifo mode (default) or switching back to legacy mode, not recommended as the CPU foot print is much higher and increases over time.

- override_sys_hostname:

This comes from the TA-nmon and is not relevant for the nmon-logger. (this allows overwriting the host value within the nmon data with the host value set in Splunk)

nmon2csv_options:

The last version implements a "fifo" mode in the parsers (nmon2kv.pl|.py) which is almost similar to the cold data mode, this instructs the parsers not to try to prevent duplication.
This is more adapted to the way things work with the fifo implementation.

I hope this answers your questions, feel free if you need more information.

Thanks

Guilhem

**Comment by guilhemmarchand** [comment]
Hi,

I have released a new version in the testing branch, with the release 2.0.2.

This should definitively solve your issue as the nmon external header is now generated into a dedicated and separated file from the named pipe.

I have also fixed the rpm upgrade issue (thanks for reporting it !), since the scriptlets are embedded within the rpm, this will be valid only starting this new version.
FYI, I have updated the "postun" scriptlet to properly manage the upgrade case.

Finally, I have fixed some nmon-logger related issues in the core application and the TA-nmon (missing indexed time field extraction for OStype and type fields, extractions failure for UPTIME and PROCCOUNT)

These new version will be released soon as well. (currently in testing branches)

Thank you for your feedback!

**Comment by zbw1983** [comment]
Thanks for your update. I will try it later and give you feedback. Before as a workaround, I disable nmon_external_start.sh, seem everything works well.

**Comment by guilhemmarchand** [comment]
Hello,

Have you add the chance to verify that the last version fixed your issue ?

Thank you,

Guilhem

**Comment by zbw1983** [comment]
Hi: 

Sorry for replying you late, in fact I install 2.0.3 version on some servers, I haven’t verify whether this issue fixed or not now, because it is not easy to find which server is wrong in hundred of servers, but I will keep watching that. 

But on this version, I found another problem, seems sometimes NMON process can’t exist, on some servers, I have more than 100 nmon process running. Below information is got from one server, it has about 300 nmon processes, and most of them are fifo_consumer.sh and nmon2kv.sh. I am not sure what’s wrong now, could you have a look? 
 

!56 # /bin/ps aux | grep nmon |wc -l
304


Process list: 

nmon     64245 64197  0 13:42 ?        00:00:00 python /etc/nmon-logger/bin/nmon2kv.py --mode fifo --use_fqdn
nmon     64642 64640  0 13:43 ?        00:00:00 /bin/sh -c /etc/nmon-logger/bin/fifo_consumer.sh >> /var/log/nmon-logger/nmon_processing.log 2>&1
nmon     64645 64642  0 13:43 ?        00:00:00 /bin/sh /etc/nmon-logger/bin/fifo_consumer.sh
nmon     64671 64645  0 13:43 ?        00:00:00 /bin/sh /etc/nmon-logger/bin/nmon2kv.sh --mode fifo --use_fqdn
nmon     64707 64671  0 13:43 ?        00:00:00 python /etc/nmon-logger/bin/nmon2kv.py --mode fifo --use_fqdn
nmon     65105 65101  0 13:44 ?        00:00:00 /bin/sh -c /etc/nmon-logger/bin/fifo_consumer.sh >> /var/log/nmon-logger/nmon_processing.log 2>&1
nmon     65109 65105  0 13:44 ?        00:00:00 /bin/sh /etc/nmon-logger/bin/fifo_consumer.sh
nmon     65162 65109  0 13:44 ?        00:00:00 /bin/sh /etc/nmon-logger/bin/nmon2kv.sh --mode fifo --use_fqdn
nmon     65206 65162  0 13:44 ?        00:00:00 python /etc/nmon-logger/bin/nmon2kv.py --mode fifo --use_fqdn

**Comment by zbw1983** [comment]
Hi Guilhem: 

I find the problem, it is not related with version, on both 2.0.3 and 2.0.0, this problem happened. On those servers,  this line "host=socket.getfqdn()” in nmon2kv.py is very slow, I enable “—use_fqdn” for nmon, then it needs run this line. 

The real problem is nmon2kv.py output lot of lines like "INFO HOSTNAME:xxxxx” on all servers, I can find more than 100,000 same lines in /var/log/nmon-logger/nmon_processing.log on each servers, while on most of servers, socket.getfqdn run fast, then I didn’t notice that, but on some servers, this line run a little slow, then this problem emerge out. 

So could you help to check why nmon2kv.py outputs so many HOSTNAME lines? many thanks. 

Regards
Bowen

**Comment by zbw1983** [comment]
many thanks. 

maybe it is a different problem, do we need open another ticket?

**Comment by guilhemmarchand** [comment]
Hello Bowen,

Thank for you this feed back, for your analysis.

I am looking at the issue, there are other corrections I have to back port to the nmon-logger package as well.

Regarding the call to the getfqdn function, the issue on those servers is probably at some point DNS or OS configuration related, but I will check if this call can be replaced or improved.

It is indeed called every time the script runs, which happens every minute.

Regards,

Guilhem

**Comment by zbw1983** [comment]
Thanks a lot. I think the problem is why it outputs so many "INFO HOSTNAME:xxxxx” lines in /var/log/nmon-logger/nmon_processing.log. getfqdn is a little slow but acceptable, it takes about 2 or 3 seconds, but if that program run it thousand of time in 1 minute, then it hang there, then next process starts again. 

Regards
Bowen

**Comment by guilhemmarchand** [comment]
Bowen,

You are perfectly correct, the call to the the getfqdn should definitively be out of the for section in the Python script.

I am verifying, I should be able to provide a corrective release quiet easily and shortly.

Guilhem

**Comment by guilhemmarchand** [comment]
in addition, in the TA-nmon equivalent: 

https://github.com/guilhemmarchand/TA-nmon/blob/master/TA-nmon/bin/nmon2csv.py

line 757, the call is out of the for loop.

**Comment by guilhemmarchand** [comment]
Hi Bowen,

A corrective release, version 2.0.4 is available in testing & release branches:

[https://github.com/guilhemmarchand/nmon-logger/tree/release](url)

This release will fixe the FQDN issue with the Python script.

Thank you in advance for your feedback.

Regards,

Guilhe,

**Comment by zbw1983** [comment]
Thanks for your quick update. I will install it on some of my servers, and keep monitoring this problem. 

Regards
Bowen
